# Generated by Django 4.0.5 on 2022-07-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='student',
            new_name='user',
        ),
    ]
