# Generated by Django 4.0.5 on 2022-07-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_books_book_issued_alter_books_cover_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='pdf',
        ),
    ]
